//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manufacrure_DE_gogolev.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        public int id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public bool IsBlocked { get; set; }
        public int CustomerID { get; set; }
        public int RoleID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
