//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manufacrure_DE_gogolev.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public UserRole()
        {
            this.SystemUser = new HashSet<SystemUser>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SystemUser> SystemUser { get; set; }
    }
}
